import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import products from '../products.json';
import logoidea from '../public/images/logoidea.png';

console.log({logoidea}.logoidea)
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lots-o'-Stitchin'</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
      </Head>
      <div className="navCart">
      <a href="#/cart" id="cart_home">
        
        </a>
      </div>
      <main className={styles.main}>
      <div className="pleaseWork" >
        <img src={logoidea.src} alt="Logoidea" />
      </div>
        
        <p className={styles.description}>
        <a className="snipcart-checkout snipcart-summary" href="#" style={{textDecoration: "none"}}>
        <svg viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg" className="snipcart-cart-header__icon snipcart__icon"  >
        <path fillRule="evenodd" clipRule="evenodd" d="M51.714 20.47L55 60H9l3.286-39.53h9.857v-6.588C22.143 8.424 26.556 4 32 4c5.444 0 9.857 4.424 9.857 9.882v6.589h9.857zM25.43
         13.883v16.47h-3.286v-6.587h-6.834l-2.737 32.94h38.856l-2.737-32.94h-6.834v6.588h-3.286v-16.47c0-3.634-2.947-6.589-6.571-6.589-3.624 0-6.571 2.955-6.571 6.588zm3.285 9.883V20.47h6.572v3.294h-6.572z" fill="#FFED03"></path>
        </svg> <span className="snipcart-total-price">$0.00</span>
          </a>
        </p>

        <div className={styles.grid}>
          {products.map(product => {
            return (
               <div key={product.id} className={styles.card}>
                <img src={product.image} alt={`Preview of ${product.title}`} /> 
                <h3>{ product.title }</h3>
                <p>{ product.description }</p>
                <p>${ product.price }</p>
                <p>
                <button className="snipcart-add-item" 
                    data-item-id={product.id}
                    data-item-image={product.image}
                    data-item-name={product.title}
                    data-item-price={product.price} fill="#FFED03">Add to Cart</button> 
                    
                </p>

      </div>
    );
  })}
</div>
      </main>

      <footer className={styles.footer}>
        
        
        <script async src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js" />
        <div hidden id="snipcart" data-api-key="OWRjMzNiOWYtNGFmYS00NzE2LTg3ZmItMjA3OTc5NTNlNzJiNjM3ODg1MjI3NzA0NDEwNjMx" />
      </footer>
    </div>
  )
}
